### ISSUE TITLE
UP FOR GRABS - No support for directories, limits usefulness in bundles

### ISSUE THREAD

**Issue by cherrydev** [mcintyre321/EmbeddedResourceVirtualPathProvider#11]
Because the Vpp doesn't implement GetDirectory or DirectoryExists, the Bundle.IncludeDirectory method doesn't work at all, which unfortunately makes it rather limiting.  I'm going to try to implement it, if that's alright with you.

**Comment by ulrichb** [comment]
Yes, would also need this feature. Without, I cannot use my "*"-Includes when using System.Web.Optimization bundles.

**Comment by MatejSpin** [comment]
I will implement this in following days.

**Comment by thorgeir** [comment]
I've made a pull request that should fulfill this issue. But it comes with one big caveat, it only works for files that have exactly one period (filename.ext)

**Comment by mcintyre321** [comment]
Awesome work @thorgeir . I'll need a bit of time to review this.

WRT the caveat - would it be possible to change is so files which contain multiple periods can be found at multuiple paths? e.g. 

`\foo\bar.baz.js`, which would become a resource `foo.bar.baz.js` would be available at all combinations of virtual paths from `/foo.bar.baz.js`, `/foo/bar.baz.js`, ..., `/foo/bar/baz.bat`, if you see what I mean?

I haven't really though this through yet, so there may be a very good reason why this won't work. 

If not though, it might be better if you could make this change, as it will stop people who aren't aware of the caveat from raising issues.

**Comment by thorgeir** [comment]
We could generate every possible combination. but the main usage for this would be with bundles and if you know about this limitation you should be able to adjust your filenames to fit the pattern. Right?

**Comment by thorgeir** [comment]
Also, if we make files accessible through all combinations, including `~/foo/*.js` in a bundle would include all .js files in all sub-directories.

**Comment by mcintyre321** [comment]
So a big problem is it's pretty common for something to be called `\js\jquery-1.5.1.min.js`, - could some client of (configurable?) heuristic be used, that works with version numbers and `.min`?

Also, would my suggestion result in multiple identical files being returned? I'm not that familiar with the ins and outs of bundling.

**Comment by thorgeir** [comment]
Some thing like this?
`http://www.rubular.com/r/VppMRdjluu`

**Comment by mcintyre321** [comment]
Very nice! Do you need the assembly name bit?

**Comment by mcintyre321** [comment]
Also, might be worth treating `.less.css`, `.ts.js` specially too... although that can be done later, `.min` is by far the most common case

**Comment by thorgeir** [comment]
The initial resource name includes the assembly name, but it could be remove that before running the regex.
Also we could also make this configurable like the CacheControl bit.
