### ISSUE TITLE
Missing strong name

### ISSUE THREAD

**Issue by boppbo** [mcintyre321/EmbeddedResourceVirtualPathProvider#12]
Hi,

could you sign the assembly with a strong name please?

Best regards

Boris

**Comment by mcintyre321** [comment]
I suggest you fork it and strong name your fork.

I don't strong name for the reasons at http://jeremydmiller.com/2014/04/28/fubumvc-lessons-learned-strong-naming-woes-and-workarounds/

**Comment by hazzik** [comment]
https://github.com/Haacked/Rothko/pull/23
