### ISSUE TITLE
Trying to get working with MVC 4

### ISSUE THREAD

**Issue by allenwilson-innovativednd** [mcintyre321/EmbeddedResourceVirtualPathProvider#15]
Hello....not sure if this is an issue...more of a request for assistance. Trying to use the library to use as part of a MVC Contrib portalable area.

I set your library up in the DLL for the portable area and put the JS files in the scripts directory. When I try adding the MVC Portable area DLL to the main MVC project (in an Area)...i am get a error with the following test JQuery ($ is undefinded)

@model dynamic

<html xmlns="http://www.w3.org/1999/xhtml">
<head >
    <title></title>
    <script src="/Scripts/jquery-1.8.2.js" ></script>

</head>
<body>
    <form id="formtest" >
        <p>Click on this paragraph.</p>
    </form>

    <script>
    $(document).ready(function () {
        $("p").click(function () {
            alert("The paragraph was clicked.");
        });
    });
    </script>

</body>
</html>

Any help is appreciated

**Comment by mcintyre321** [comment]
Have you set the scripts to be embedded resources?

**Comment by allenwilson-innovativednd** [comment]
Yes....I have......trying to pull in jquery-1.8.2.js

**Comment by allenwilson-innovativednd** [comment]
i can zip up my sample and send it...if you want to take a look

**Comment by allenwilson-innovativednd** [comment]
From what i can tell by stepping through things...it has the file but it does not allow it to work correctly (i.e. making function calls, loading JQuery functions)

**Comment by allenwilson-innovativednd** [comment]
Please close this issue....I found out what it was.....the name assigned to the assembly

**Comment by mcintyre321** [comment]
No problem, glad you figured it out. If you have the time, it would be great if you could update the rename or wiki with something to help others avoid your issue.
