### ISSUE TITLE
Does not work in IIS

### ISSUE THREAD

**Issue by Serboy** [mcintyre321/EmbeddedResourceVirtualPathProvider#16]
Hi, I have a problem when I deployed it on my local iis, "The view 'Frontend/Default' or its master was not found or no view engine supports the searched locations. The following locations were searched:"
any suggestions on how to fixt this?

Thanks,
Renz

**Comment by mcintyre321** [comment]
It's a bit weird that the locations searched is empty. Have you unregisted the default view engine, or cleared out it's search paths? Do other non-embbed views in the host project work?

Does the example project in this project work if you download it locally?

Also make sure

a/ registered the VPP
b/ embedded the resource
