### ISSUE TITLE
Is this work for Asp.net 5? (Asp.net vNext, Asp.net MVC 6)

### ISSUE THREAD

**Issue by alexsandro-xpt** [mcintyre321/EmbeddedResourceVirtualPathProvider#17]
I'm looking for module development like this http://www.codeproject.com/Articles/614767/NET-ASP-NET-MVC-plug-in-architecture-with-embedded and wish work with asp.net vnext.

**Comment by mcintyre321** [comment]
Nope - at some point I will have to get round to creating a fork for vnext which will use the https://github.com/aspnet/FileSystem instead of a VPP

**Comment by mcintyre321** [comment]
Might be worth tryin g
https://github.com/aspnet/FileSystem/blob/dev/src/Microsoft.AspNet.FileProviders.Embedded/EmbeddedFileProvider.cs

**Comment by alexsandro-xpt** [comment]
Nice, but I do not have any idea how it could will work together view engine.
I found another ideias, take a look:

http://www.jeffreyfritz.com/2015/05/customize-asp-net-mvc-6-view-location-easily/
http://weblogs.asp.net/imranbaloch/view-location-expander-aspnet5-mvc6
https://weblogs.asp.net/imranbaloch/custom-viewengine-aspnet5-mvc6
