### ISSUE TITLE
Usage with MVC bundles

### ISSUE THREAD

**Issue by MatejSpin** [mcintyre321/EmbeddedResourceVirtualPathProvider#19]
Hello,

First thanks for this great project, it has helped me a lot. But now I ran into a problem I don't know how to solve...

I'm trying to use EmbeddedResourceVirtualPathProvider as VirtualPathProvider for MVC bundles..

However I have a problem that my bundles are not refreshing when I edit files.

Here's my usage:
   BundleTable.VirtualPathProvider = new Vpp(BundleTable.VirtualPathProvider)
            {
                {typeof (BundleConfig).Assembly, @"\"},
            };

It does not work if file is embeded or not... Not sure on how to solve this issue.

Thanks for any help !

**Comment by mcintyre321** [comment]
I'm not sure whats wrong. If you update the example project to use Mvc bundles, and push that to a branch, I could take a look.

**Comment by mcintyre321** [comment]
This is probably related to https://github.com/mcintyre321/EmbeddedResourceVirtualPathProvider/issues/11
