### ISSUE TITLE
Simple support for a little diagnostics

### ISSUE THREAD

**Issue by Dashue** [mcintyre321/EmbeddedResourceVirtualPathProvider#20]
Hey, good work on this lib!
Wanted to share a thought I had just recently.
I'm currently doing this and it works.

            var modules = BuildManager.GetReferencedAssemblies()
                .Cast<Assembly>()
                .Where(assembly => assembly
                    .GetTypes()
                    .Any(x => x.IsClass && x.GetInterfaces().Contains(typeof (IModuleConfiguration))));

            var virtualPathProvider = new Vpp2(modules.ToArray());
            {
                //you can do a specific assembly registration too. If you provide the assemly source path, it can read
                //from the source file so you can change the content while the app is running without needing to rebuild
                //{typeof(SomeAssembly.SomeClass).Assembly, @"..\SomeAssembly"} 
            };

            logger.Info(" Loading the following modules");
            foreach (var item in modules)
            {
                logger.Info(item.GetName().Name);
            }
            logger.Info(" Finished loading modules");

            logger.Info(" Listing embedded module resources");
            foreach (var item in virtualPathProvider.resources)
            {
                logger.Info(item.Key);
            }
            logger.Info(" Finished listing the embedded module resources");
            
            HostingEnvironment.RegisterVirtualPathProvider(virtualPathProvider);

However if VPP exposed the names of the loaded modules and resources this woul dbe easier.
VPP2 is just VPP with the resouces property set to public.

Looking forward to your thoughts

**Comment by mcintyre321** [comment]
I'd be happy to accept a pull request with the resources exposed as a public readonly property.

**Comment by Dashue** [comment]
I wasn't sure if some abstraction on top of it was preferred?
Perhaps expose collection of LoadedAssemblyNames and EmbeddedResourceNames?
Otherwise I'll pull request the exposed resources property shortly
