### ISSUE TITLE
VPP Not Working on Integrated IIS7 Azure

### ISSUE THREAD

**Issue by nickelnext** [mcintyre321/EmbeddedResourceVirtualPathProvider#33]
Hi.

We have deployed our solution on Azure using pre-compilation option while publishing, and none of the resources from the DLL (so i'm talking about the Embedded resource: may they be js, css or cshtml) get loaded. 

Without pre-compiling, it works great.

Are you aware of this issue?

Thanks

**Comment by mcintyre321** [comment]
Think you are out of luck:

"If a Web site is precompiled for deployment, content provided by a
VirtualPathProvider instance is not compiled, and no
VirtualPathProvider instances
are used by the precompiled site."
From
https://msdn.microsoft.com/en-us/library/system.web.hosting.virtualpathprovider.aspx

**Comment by mcintyre321** [comment]
This might be useful - https://github.com/RazorGenerator/RazorGenerator "Custom Tool for Visual Studio that allows processing Razor files at design time instead of runtime, allowing them to be built into an assembly for simpler reuse and distribution."

**Comment by nickelnext** [comment]
Thanks man.

But with VPP i have .js and .css in the "core" library as well as the .cshtml files.

With RazorGen i ain't sure i will be able to avoid "duplication" of js and css files.

- Core
- Specific1
- Specific2

So the two Specific projs should be loading resources and cshtml from Core.
Do you think it will be possible?

Anyway many thanks
